// Seed data for career roles, resources, and projects.
// These power the Career Paths page and the recommendations engine.

export const SEED_CAREER_ROLES = [
  {
    slug: "full-stack-developer",
    name: "Full Stack Developer",
    description:
      "Build complete web applications from UI to APIs and databases.",
    requiredSkills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "PostgreSQL",
      "REST APIs",
      "Git",
    ],
    recommendedSkills: [
      "Next.js",
      "Docker",
      "AWS",
      "GraphQL",
      "Redis",
      "Testing",
    ],
    difficulty: "Intermediate",
    prepWeeks: 10,
    icon: "Layers",
  },
  {
    slug: "frontend-developer",
    name: "Frontend Developer",
    description:
      "Craft beautiful, performant, accessible user interfaces with modern frameworks.",
    requiredSkills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "TypeScript",
      "Responsive Design",
    ],
    recommendedSkills: ["Next.js", "Tailwind CSS", "Framer Motion", "Testing"],
    difficulty: "Beginner",
    prepWeeks: 8,
    icon: "Layout",
  },
  {
    slug: "backend-developer",
    name: "Backend Developer",
    description:
      "Design scalable APIs, data models, and server-side architecture.",
    requiredSkills: [
      "Node.js",
      "Express",
      "PostgreSQL",
      "REST APIs",
      "Authentication",
      "Docker",
    ],
    recommendedSkills: ["Redis", "GraphQL", "Kafka", "AWS", "System Design"],
    difficulty: "Intermediate",
    prepWeeks: 10,
    icon: "Server",
  },
  {
    slug: "ai-ml-engineer",
    name: "AI/ML Engineer",
    description:
      "Train, deploy, and monitor intelligent models that solve real problems.",
    requiredSkills: [
      "Python",
      "Machine Learning",
      "Statistics",
      "Deep Learning",
      "TensorFlow",
      "SQL",
    ],
    recommendedSkills: [
      "MLOps",
      "Docker",
      "AWS",
      "PyTorch",
      "LLMs",
      "LangChain",
    ],
    difficulty: "Advanced",
    prepWeeks: 12,
    icon: "Brain",
  },
  {
    slug: "data-scientist",
    name: "Data Scientist",
    description:
      "Turn messy data into insight, predictions, and decisions.",
    requiredSkills: [
      "Python",
      "SQL",
      "Statistics",
      "Pandas",
      "Visualization",
      "Machine Learning",
    ],
    recommendedSkills: ["Spark", "A/B Testing", "BigQuery", "Tableau"],
    difficulty: "Intermediate",
    prepWeeks: 10,
    icon: "BarChart3",
  },
  {
    slug: "devops-engineer",
    name: "DevOps Engineer",
    description:
      "Automate, scale, and keep production systems healthy and secure.",
    requiredSkills: [
      "Linux",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "AWS",
      "Terraform",
    ],
    recommendedSkills: ["Ansible", "Prometheus", "GitOps", "Bash"],
    difficulty: "Advanced",
    prepWeeks: 12,
    icon: "Rocket",
  },
  {
    slug: "cybersecurity-engineer",
    name: "Cybersecurity Engineer",
    description:
      "Protect systems, networks, and data from modern threats.",
    requiredSkills: [
      "Networking",
      "Linux",
      "Cryptography",
      "OWASP",
      "SIEM",
      "Python",
    ],
    recommendedSkills: ["Penetration Testing", "Cloud Security", "Incident Response"],
    difficulty: "Advanced",
    prepWeeks: 14,
    icon: "Shield",
  },
  {
    slug: "cloud-engineer",
    name: "Cloud Engineer",
    description:
      "Architect and operate cloud infrastructure at scale.",
    requiredSkills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Networking",
      "Linux",
    ],
    recommendedSkills: ["GCP", "Azure", "Serverless", "Observability"],
    difficulty: "Intermediate",
    prepWeeks: 10,
    icon: "Cloud",
  },
];

export const SEED_RESOURCES = [
  // Full Stack / Frontend
  {
    title: "MDN Web Docs — JavaScript Guide",
    skill: "JavaScript",
    platform: "MDN",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    type: "Documentation",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 12,
    description: "The definitive reference for modern JavaScript.",
  },
  {
    title: "React Official Tutorial",
    skill: "React",
    platform: "react.dev",
    url: "https://react.dev/learn",
    type: "Documentation",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 10,
    description: "Learn React from the source, with hands-on examples.",
  },
  {
    title: "TypeScript Handbook",
    skill: "TypeScript",
    platform: "typescriptlang.org",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    type: "Documentation",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 8,
    description: "Master TypeScript fundamentals and advanced patterns.",
  },
  {
    title: "Next.js Learn",
    skill: "Next.js",
    platform: "nextjs.org",
    url: "https://nextjs.org/learn",
    type: "Course",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 14,
    description: "Build a full app with the App Router.",
  },
  // Backend
  {
    title: "Node.js Best Practices",
    skill: "Node.js",
    platform: "GitHub",
    url: "https://github.com/goldbergyoni/nodebestpractices",
    type: "Documentation",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 10,
    description: "Curated Node.js best practices from the community.",
  },
  {
    title: "PostgreSQL Tutorial",
    skill: "PostgreSQL",
    platform: "postgresqltutorial.com",
    url: "https://www.postgresqltutorial.com/",
    type: "Documentation",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 12,
    description: "Learn PostgreSQL from scratch with examples.",
  },
  // AI/ML
  {
    title: "Fast.ai Practical Deep Learning",
    skill: "Deep Learning",
    platform: "fast.ai",
    url: "https://course.fast.ai/",
    type: "Course",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 40,
    description: "Top-rated free deep learning course.",
  },
  {
    title: "Kaggle ML Micro-Courses",
    skill: "Machine Learning",
    platform: "Kaggle",
    url: "https://www.kaggle.com/learn",
    type: "Course",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 20,
    description: "Hands-on mini-courses in Python, ML, SQL, and more.",
  },
  {
    title: "3Blue1Brown — Neural Networks",
    skill: "Deep Learning",
    platform: "YouTube",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    type: "Video",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 3,
    description: "Visual intuition for how neural networks work.",
  },
  {
    title: "Python for Data Science Handbook",
    skill: "Python",
    platform: "jakevdp.github.io",
    url: "https://jakevdp.github.io/PythonDataScienceHandbook/",
    type: "Book",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 20,
    description: "NumPy, Pandas, Matplotlib, Scikit-Learn in one place.",
  },
  // DevOps / Cloud
  {
    title: "Docker Getting Started",
    skill: "Docker",
    platform: "docker.com",
    url: "https://docs.docker.com/get-started/",
    type: "Documentation",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 6,
    description: "Official Docker tutorial.",
  },
  {
    title: "AWS Free Tier + Cloud Practitioner",
    skill: "AWS",
    platform: "AWS",
    url: "https://aws.amazon.com/training/",
    type: "Course",
    difficulty: "Beginner",
    isFree: true,
    durationHours: 15,
    description: "Start your cloud journey with AWS official training.",
  },
  {
    title: "Kubernetes the Hard Way",
    skill: "Kubernetes",
    platform: "GitHub",
    url: "https://github.com/kelseyhightower/kubernetes-the-hard-way",
    type: "Tutorial",
    difficulty: "Advanced",
    isFree: true,
    durationHours: 16,
    description: "Deep dive into how Kubernetes actually works.",
  },
  // Security
  {
    title: "OWASP Top 10",
    skill: "OWASP",
    platform: "owasp.org",
    url: "https://owasp.org/www-project-top-ten/",
    type: "Documentation",
    difficulty: "Intermediate",
    isFree: true,
    durationHours: 6,
    description: "The most critical web app security risks.",
  },
];

export const SEED_PROJECTS = [
  {
    title: "Personal Portfolio with Next.js",
    description:
      "Build a polished portfolio with a blog, projects, and contact form.",
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    difficulty: "Beginner",
    technologies: ["Next.js", "Tailwind", "MDX"],
    features: [
      "Project showcase grid",
      "Blog with MDX",
      "Dark mode",
      "Contact form",
    ],
    outcomes: [
      "Deploy to production",
      "SEO-ready",
      "Performance-optimized",
    ],
  },
  {
    title: "Task API with Node + PostgreSQL",
    description:
      "REST API for tasks with authentication, validation, and tests.",
    skills: ["Node.js", "PostgreSQL", "REST APIs", "Authentication"],
    difficulty: "Intermediate",
    technologies: ["Express", "PostgreSQL", "Drizzle", "JWT"],
    features: [
      "CRUD endpoints",
      "JWT auth",
      "Pagination + filters",
      "Unit + integration tests",
    ],
    outcomes: ["Clean REST design", "Production-grade auth", "Tested code"],
  },
  {
    title: "Movie Recommender",
    description:
      "A recommender system using collaborative filtering.",
    skills: ["Python", "Machine Learning", "Pandas", "Flask"],
    difficulty: "Intermediate",
    technologies: ["Python", "Scikit-Learn", "Flask"],
    features: [
      "Data cleaning pipeline",
      "Similarity matrix",
      "Web UI",
      "API endpoint",
    ],
    outcomes: [
      "Recommender fundamentals",
      "End-to-end ML",
      "Deployed demo",
    ],
  },
  {
    title: "Dockerized Chat App",
    description:
      "Real-time chat with Docker Compose and a reverse proxy.",
    skills: ["Docker", "Node.js", "WebSockets"],
    difficulty: "Intermediate",
    technologies: ["Docker", "Node.js", "Nginx"],
    features: [
      "Realtime messaging",
      "Multi-container compose",
      "Reverse proxy",
    ],
    outcomes: ["Containerization", "Networking", "Compose mastery"],
  },
  {
    title: "Sentiment Analysis Dashboard",
    description:
      "Streamlit app that analyzes and visualizes sentiment over time.",
    skills: ["Python", "NLP", "Visualization"],
    difficulty: "Intermediate",
    technologies: ["Python", "Streamlit", "Hugging Face"],
    features: [
      "Text upload",
      "Sentiment scores",
      "Charts over time",
    ],
    outcomes: ["Applied NLP", "Dashboard design", "Model deployment"],
  },
  {
    title: "CI/CD Pipeline on GitHub Actions",
    description:
      "Build, test, and deploy an app on every push.",
    skills: ["CI/CD", "Docker", "Git"],
    difficulty: "Intermediate",
    technologies: ["GitHub Actions", "Docker", "AWS"],
    features: [
      "Lint + test jobs",
      "Build image",
      "Deploy to staging",
    ],
    outcomes: ["Automation", "Reliable releases", "Modern DevOps"],
  },
];
